# Generated by Django 6.0.6 on 2026-08-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('Half Day', 'Half Day'), ('Leave', 'Leave')], default='Present', max_length=20),
        ),
    ]
